# app/streamlit_app.py
import streamlit as st
import requests
import os
from dotenv import load_dotenv

load_dotenv()

API_URL = os.getenv("LOCAL_API_URL", "http://localhost:8000")  

st.set_page_config(page_title="FitAI Planner", layout="wide", page_icon="🏋️‍♀️")

# Header
col1, col2 = st.columns([4,1])
with col1:
    st.title("FitAI Planner")
    st.markdown("Personalized meal & workout plans — generated by agents.")
with col2:
    st.image("https://images.unsplash.com/photo-1542444459-db7d7a2a4f2b?auto=format&fit=crop&w=200&q=60", width=100)

# Onboarding - side panel
st.sidebar.header("Your profile")
with st.sidebar.form("profile_form"):
    name = st.text_input("Name", value="Alex")
    age = st.number_input("Age", min_value=12, max_value=90, value=28)
    gender = st.selectbox("Gender", ["Male","Female","Other"])
    weight = st.number_input("Weight (kg)", min_value=20, max_value=300, value=70)
    height = st.number_input("Height (cm)", min_value=100, max_value=230, value=170)
    activity_level = st.selectbox("Activity", ["Sedentary","Light","Moderate","Active","Very active"])
    goal = st.selectbox("Goal", ["Lose weight","Gain muscle","Maintain"])
    allergies = st.text_input("Allergies (comma-separated)", value="")
    cuisine_pref = st.selectbox("Cuisine preference", ["Any","Indian","Mediterranean","Vegetarian","Vegan","Keto"])
    submit = st.form_submit_button("Save profile")

if submit:
    profile = {
        "name": name, "age": age, "gender": gender,
        "weight": weight, "height": height,
        "activity_level": activity_level, "goal": goal,
        "allergies": allergies, "cuisine_pref": cuisine_pref
    }
    st.success("Profile saved locally. You can generate a plan now.")
    st.session_state["profile"] = profile

# Main area - generate plan
st.markdown("## Generate Plan")
colA, colB = st.columns([2,1])
with colA:
    st.info("Click the button to generate a 7-day meal + workout plan based on your profile.")
    if st.button("Generate 7-day plan"):
        if "profile" not in st.session_state:
            st.warning("Please fill out profile in the sidebar first.")
        else:
            profile = st.session_state["profile"]
            with st.spinner("Generating plan (this may take ~10s)..."):
                # Call backend orchestrator (fastapi) - or call python function directly
                try:
                    res = requests.post(f"{API_URL}/generate-plan", json=profile, timeout=60)
                    res.raise_for_status()
                    plan = res.json()
                    st.success("Plan generated!")
                    st.json(plan)  # Replace with nicer rendering below
                except Exception as e:
                    st.error(f"Error generating plan: {e}")

with colB:
    st.markdown("### Quick tips")
    st.write("""
    - Fill your profile with accurate data.
    - Use `Allergies` to block foods.
    - After generating, you can export grocery list or swap meals.
    """)
